name: LaTeX Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Compile LaTeX to PDF
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up LaTeX
        uses: dante-ev/latex-action@latest
        with:
          root_file: wzaldivar_cv_en.tex
          compiler: pdflatex

      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-pdf
          path: ./wzaldivar_cv_en.pdf

  release:
    name: Release PDF
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: compiled-pdf
          path: ./

      - run: gh release delete latest --cleanup-tag --yes

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: latest
          release_name: Latest
          draft: false
          prerelease: false

      - name: Upload PDF to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./wzaldivar_cv_en.pdf
          asset_name: wzaldivar_cv_en.pdf
          asset_content_type: application/pdf
